services:
  nginx:
    restart: unless-stopped
    depends_on: [ webserver ]
    networks: [ net-presence ]
    ports:
      - "127.0.0.1:80:80"
    env_file: [ .env ]
    environment:
      - POSTGRES_HOST=postgres
      - RUST_LOG=${RUST_LOG-info,webserver=debug}
      - POSTGRES_PORT=${POSTGRES_PORT-5432}
      - POSTGRES_USER=${POSTGRES_USER-postgres}
    volumes:
      - ./data/conf/nginx/presence.conf:/etc/nginx/conf.d/default.conf
    build:
      dockerfile: build/dockerfiles/nginx.Dockerfile

  webserver:
    restart: unless-stopped
    depends_on: [ postgres ]
    networks: [ net-presence ]
    env_file: [ .env ]
    build:
      dockerfile: build/dockerfiles/webserver.Dockerfile
  
  postgres:
    restart: unless-stopped
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    networks: [ net-presence ]
    volumes:
      - vol-postgres:/var/lib/postgresql/data/
    env_file: [ .env ]
    build:
      dockerfile: build/dockerfiles/postgres.Dockerfile

volumes:
  vol-postgres:

networks:
  net-presence:
    driver: bridge